### ISSUE TITLE
Fellowship awardee photos

### ISSUE THREAD

**Issue by kushinauwu** [kushinauwu/OBF-Homepage-New#26]
- [x] Use fellowship awardees' photos instead of icons in fellowships page

- [x] Use photos in travel fellowships section on homepage

**Comment by kushinauwu** [comment]
Used Farah's picture for the homepage :D Should the same picture be used on the fellowships page? Or maybe a different one would be better?

**Comment by yochannah** [comment]
yeah, it's probably best to have different pics across the site pages!

**Comment by kushinauwu** [comment]
What could be an appropriate photo for the travel awards page? (Sorry I keep asking this, but I really couldn't choose! )

**Comment by yochannah** [comment]
hmmm, most of our travel fellowship blogs don't have much in the way of photos. The only other close-up I can find [is of Farah again](https://news.open-bio.org/2018/08/18/city-of-roses-they-call-it-portland-oregon-usa/) 😆 which is okay but it might be nicer to have a little more variance. Um, I need to think a little more.

**Comment by nlharris** [comment]
One of our awardees, Anisha Keshavan, used a photo on her blog post (https://www-dev1.open-bio.org/2018/05/22/saving-science-from-itself-2018-elife-innovation-sprint/) which presumably she had permission to post. Could we use that? https://pbs.twimg.com/media/Dc7Gw6PWsAA7AQk.jpg
(We could try emailing Anisha to ask her permission to use it, but since it already appears on our blog, that's presumably not necessary)

**Comment by yochannah** [comment]
nice idea!

**Comment by nlharris** [comment]
other possibilities:
- move photo of Farah from home page to travel fellowship page; use another photo on home page
- copy photo of Farah from home page to travel fellowship page
- I found a photo of a past awardee on this blog post: https://www-dev1.open-bio.org/2018/01/30/arun-decano-awarded-obf-travel-fellowship/
since she gave permission to use the photo on that blog post, i think it would be ok to use it on the website.

**Comment by kushinauwu** [comment]
I think the first option sounds good. Maybe we could use the photo from [https://pbs.twimg.com/media/Dc7Gw6PWsAA7AQk.jpg](url) for the homepage, and use the pictures of Farah and Arun on the travel fellowships page?

**Comment by nlharris** [comment]
No, we can't use that photo from Anisha's blog post on the home page because it's not a photo of BOSC or any OBF event; it's from a different conference (which she attended with help from our travel fellowship).

**Comment by kushinauwu** [comment]
Oh, alright. Maybe we could have just Farah on the homepage, Arun's picture on the travel fellowships page. I wonder if it will seem good with one picture? 
Can Anisha's blog photo be used for the travel fellowships page?

**Comment by nlharris** [comment]
Yes, we can keep Farah on the homepage and use Anisha's blog photo and/or Arun's photo on the travel fellowships page.

**Comment by kushinauwu** [comment]
Used Anisha's blog photo for the travel fellowships page!

**Comment by nlharris** [comment]
Thanks, looks good

**Comment by yochannah** [comment]
Let's add Anisha's name to the page.
