### ISSUE TITLE
Reduce and keep spacing the same on all pages

### ISSUE THREAD

**Issue by kushinauwu** [kushinauwu/OBF-Homepage-New#28]

**Comment by kushinauwu** [comment]
the spacing before elements looks alright now, but i may have missed some places. Need help with checking that, and alignments. :)

**Comment by yochannah** [comment]
@nlharris when you have a moment to check could you see if you like the spacing better? :)

**Comment by yochannah** [comment]
Let's making spacing a little narrower still

**Comment by nlharris** [comment]
Some places that I think could be more compact:
- home page: whitespace above/below travel fellowships section
- spacing below associated projects icons (i think this is also mentioned in another issue)
- board of directors section--make photos smaller and closer together. should be able to fit 4 per line rather than 3.
- (Not related to spacing): can you make that "See all members" button say "More about the OBF Board"
- Join us section: smaller icons

**Comment by kushinauwu** [comment]
I think most of this is fixed now. But I'll keep this open till I check every page.

**Comment by kushinauwu** [comment]
I checked the other pages too. Everything seems fine now! I'll mark this for review :D

**Comment by nlharris** [comment]
Spacing looks more consistent now!
