### ISSUE TITLE
Update board member descriptions

### ISSUE THREAD

**Issue by peterjc** [kushinauwu/OBF-Homepage-New#37]
I recently noticed some inconsistencies in the BOSC chairing information on the old Board page, which I partly updated - and now differs from the new board page https://www-dev1.open-bio.org/board/ vs https://www.open-bio.org/wiki/Board

If we want to keep BOSC dates, we can probably say for @nlharris something like "BOSC chair or co-chair since 2011".  And for @HlWiencko, "BOSC co-chair since 2017". In my case, "BOSC co-chair 2015 & 2016" (as currently done on the old wiki).

Or, if we just want so list the current BOSC co-chairs, that's Nomi & Heather?

**Comment by nlharris** [comment]
Thanks, Peter. I noticed those too but figured I'd just update the text myself. The key thing we need to communicate to Deepashree before the end of the month is any style issues. Those are harder to change by ourselves (though still possible).

**Comment by kushinauwu** [comment]
Ah, sorry! I hadn't checked the Board page on https://www.open-bio.org/wiki/Board recently, so I wasn't aware of the edits :)
All the content can be updated at any time though! I'd suggest waiting a bit before updating it because when I push content it might get overwritten. I'll be happy to update it as the current information stands on the open-bio page! :)
